#!/usr/bin/env python3
"""Compile the Vulkan GLSL under src/recomp/host/gpu/vulkan/shaders/ into
shaders_spv.h (`compile`), or recompile into a scratch file and fail on any
difference from the committed header (`check`)."""
import argparse
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SHADERS = ROOT / "src/recomp/host/gpu/vulkan/shaders"
HEADER = ROOT / "src/recomp/host/gpu/vulkan/shaders_spv.h"
GLSLC_ARGS = ["-O", "--target-env=vulkan1.1", "-Werror"]


def compile_one(glslc, src, out_dir):
    spv = Path(out_dir) / (src.name + ".spv")
    subprocess.run([glslc, *GLSLC_ARGS, str(src), "-o", str(spv)], check=True)
    data = spv.read_bytes()
    if len(data) % 4:
        raise SystemExit(f"{src.name}: SPIR-V length is not a multiple of 4")
    return [int.from_bytes(data[i:i + 4], "little") for i in range(0, len(data), 4)]


def glslc_version(glslc):
    out = subprocess.run([glslc, "--version"], capture_output=True, text=True, check=True).stdout
    return out.strip().splitlines()[0].strip()


def render(programs, version):
    lines = ["// shaders_spv.h - generated by tools/recomp/shaders.py from gpu/vulkan/shaders/.",
             "// Do not edit; `python3 tools/recomp/shaders.py compile` regenerates it.",
             f"// glslc: {version}",
             "#pragma once", "#include <stddef.h>", "#include <stdint.h>", "",
             "namespace gpu::vulkan {", "",
             "struct SpirvProgram {", "    const char *name;", "    const uint32_t *words;",
             "    size_t count;", "};", ""]
    for name, words in programs:
        ident = "k_" + name.replace(".", "_")
        lines.append(f"static const uint32_t {ident}[{len(words)}] = {{")
        for i in range(0, len(words), 8):
            lines.append("    " + ", ".join(f"0x{w:08x}" for w in words[i:i + 8]) + ",")
        lines.append("};")
    lines.append("")
    lines.append("static const SpirvProgram kSpirvPrograms[] = {")
    for name, words in programs:
        ident = "k_" + name.replace(".", "_")
        lines.append(f'    {{"{name}", {ident}, {len(words)}}},')
    lines.append("    {nullptr, nullptr, 0},")
    lines.append("};")
    lines.append("")
    lines.append("} // namespace gpu::vulkan")
    return "\n".join(lines) + "\n"


def build():
    glslc = shutil.which("glslc")
    if not glslc:
        raise SystemExit("glslc not found; brew install shaderc (macOS) or apt install glslc")
    sources = sorted(p for p in SHADERS.iterdir() if p.suffix in (".vert", ".frag", ".comp"))
    version = glslc_version(glslc)
    with tempfile.TemporaryDirectory() as tmp:
        return render([(s.name, compile_one(glslc, s, tmp)) for s in sources], version)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=["compile", "check"])
    args = parser.parse_args()
    if args.command == "check" and HEADER.exists():
        # A different glslc emits different but equivalent SPIR-V; only the
        # recorded compiler can judge drift.
        recorded = next((l[10:] for l in HEADER.read_text().splitlines()
                         if l.startswith("// glslc: ")), "")
        current = glslc_version(shutil.which("glslc"))
        if recorded != current:
            print(f"skipped: header built with '{recorded}', this glslc is '{current}'")
            return 0
    text = build()
    if args.command == "compile":
        HEADER.write_text(text)
        print(f"wrote {HEADER.relative_to(ROOT)}")
        return 0
    if not HEADER.exists() or HEADER.read_text() != text:
        print("shaders_spv.h is out of date: run `python3 tools/recomp/shaders.py compile`",
              file=sys.stderr)
        return 1
    print("shaders_spv.h matches the GLSL sources")
    return 0


if __name__ == "__main__":
    sys.exit(main())
